[package]
name = "pommedapi"
version = "2.1.0"
authors = ["Guillaume Friloux <guillaume@friloux.me>"]

[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"
reqwest = "0.9.12"
getopts = "0.2"
tempfile = "*"
handlebars = "^0.29"
fs_extra = "*"
indicatif = "*"
